config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  resources :projects



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <a class="navbar-brand" href="#">azeelist</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><i class="fas fa-arrow-circle-down"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Raleway|Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <title>Azeelist</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/index.html.erb
<main class="container project-dashboard">
  <div class="row project-dashboard-header">

    <div class="col-md-1 mr-auto">
      <button type="button" class="project-button-style mr-auto">
        <%= link_to 'New', new_project_path, class: "new-project-button" %>
      </button>
    </div>

    <div class="col-md-4">
      <h4 class="text-center project-title-name">Projects</h4>
    </div>
    <div class="col-md-1 ml-auto">
      <button class="btn dots-button ml-auto">...</button>
    </div>
  </div><!-- row -->

  <div class="row checklist-cards">
    <div class="col-md-4 checklist-col">
      <a href="#" class="checklist-card">
        <h4>Checklist Name</h4>
        <ul class="items-list">
          <li>item-1</li>
          <li>item-2</li>
          <li>item-3</li>
        </ul>
      </a>
    </div>
    <div class="col-md-4 checklist-col">
      <a href="#" class="checklist-card">
        <h4>Checklist Name</h4>
        <ul class="items-list">
          <li>item-1</li>
          <li>item-2</li>
          <li>item-3</li>
        </ul>
      </a>
    </div>
    <div class="col-md-4 checklist-col">
      <a href="#" class="checklist-card">
        <h4>Checklist Name</h4>
        <ul class="items-list">
          <li>item-1</li>
          <li>item-2</li>
          <li>item-3</li>
        </ul>
      </a>
    </div>
  </div>


</div><!-- container -->

app/views/welcome/index.html.erb
<div class="container welcome-container">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag("planner-and-marker.jpg", class: "d-block w-100", alt: "planner-and-marker") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("yellow-flowers.jpg",  class: "d-block w-100", alt: "yellow-flowers") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("yellow-tulips.jpg", class: "d-block w-100", alt: "yellow-tulips") %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div> 
</div>